apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-operator-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-operator-helm
  template:
    metadata:
      labels:
        name: memcached-operator-helm
    spec:
      serviceAccountName: memcached-operator-helm
      containers:
        - name: memcached-operator-helm
          # Replace this with the built image name
          image: quay.io/btenneti/memcached-helm-demo:v0.0.3
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memcached-operator-helm"
